spring:
  flyway:
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 杀伤力太大了, 应该禁掉.
    clean-disabled: true
    # 启用或禁用 flyway
    enabled: true
    # 设定 SQL 脚本的目录,多个路径使用逗号分隔, 比如取值为 classpath:db/migration
    locations: db/migration
    sql-migration-prefix: V
    sql-migration-suffixes:
    - .sql
    sql-migration-separator: _
    # 如果指定 schema 包含了其他表,但没有 flyway schema history 表的话, 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令.
    # 设置 spring.flyway.baseline-on-migrate 为 true 后, flyway 将在需要 baseline 的时候, 自动执行一次 baseline.
    baseline-on-migrate: true
    # 指定 baseline 的版本号,缺省值为 1, 低于该版本号的 SQL 文件, migrate 的时候被忽略.
    baseline-version: 0.0.0
    # Encoding of SQL migrations (default: UTF-8)
    encoding: UTF-8
    # 设定 flyway 的 metadata 表名, 缺省为 flyway_schema_history
    table: flyway_schema_history
    # 开发环境最好开启 outOfOrder, 生产环境关闭 outOfOrder
    out-of-order: false
    check-location: false
    baseline-description: initialize    
    
  application:
    name: demo-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  servlet:
    multipart:
      # 开启 multipart 上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大请求大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB
      
server:
  port: 8502
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/

file:
  upload-dir: /uploads/

login:
  name: admin
  password: admin